<?xml version="1.0" encoding="utf-8"?>

<Project>
    <PropertyGroup Condition="'$(Configuration)' == 'NoDisconnect'">
        <DefineConstants>$(DefineConstants);DEBUG;NO_DISCONNECT</DefineConstants>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <OutputPath>bin\NoDisconnect\</OutputPath>
        <DebugSymbols>true</DebugSymbols>
        <IntermediateOutputPath>obj\NoDisconnect\</IntermediateOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Testing'">
        <DefineConstants>$(DefineConstants);DEBUG;TESTING</DefineConstants>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <OutputPath>bin\Testing\</OutputPath>
        <DebugSymbols>true</DebugSymbols>
        <IntermediateOutputPath>obj\Testing\</IntermediateOutputPath>
    </PropertyGroup>
</Project>