//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WukongMp.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuiltinTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuiltinTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WukongMp.Api.Resources.BuiltinTexts", typeof(BuiltinTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected to the server elsewhere..
        /// </summary>
        public static string AlreadyConnected {
            get {
                return ResourceManager.GetString("AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engage!.
        /// </summary>
        public static string AntiStallWarning {
            get {
                return ResourceManager.GetString("AntiStallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were banned from the server..
        /// </summary>
        public static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Blue.
        /// </summary>
        public static string BlueTeam {
            get {
                return ResourceManager.GetString("BlueTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string CameraDownControls {
            get {
                return ResourceManager.GetString("CameraDownControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string CameraDownDescription {
            get {
                return ResourceManager.GetString("CameraDownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W S A D.
        /// </summary>
        public static string CameraMoveControls {
            get {
                return ResourceManager.GetString("CameraMoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string CameraMoveDescription {
            get {
                return ResourceManager.GetString("CameraMoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMB.
        /// </summary>
        public static string CameraRotateControls {
            get {
                return ResourceManager.GetString("CameraRotateControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string CameraRotateDescription {
            get {
                return ResourceManager.GetString("CameraRotateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←/→.
        /// </summary>
        public static string CameraSwitchControls {
            get {
                return ResourceManager.GetString("CameraSwitchControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch player.
        /// </summary>
        public static string CameraSwitchDescription {
            get {
                return ResourceManager.GetString("CameraSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string CameraUpControls {
            get {
                return ResourceManager.GetString("CameraUpControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string CameraUpDescription {
            get {
                return ResourceManager.GetString("CameraUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER - Type/Send   |   K - Hide/Show Chat.
        /// </summary>
        public static string ChatHelperDescription {
            get {
                return ResourceManager.GetString("ChatHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K - Hide/Show Event Log.
        /// </summary>
        public static string ChatHelperNoSendDescription {
            get {
                return ResourceManager.GetString("ChatHelperNoSendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheats are disabled.
        /// </summary>
        public static string CheatsAreDisabled {
            get {
                return ResourceManager.GetString("CheatsAreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheats disabled.
        /// </summary>
        public static string CheatsDisabled {
            get {
                return ResourceManager.GetString("CheatsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheats enabled.
        /// </summary>
        public static string CheatsEnabled {
            get {
                return ResourceManager.GetString("CheatsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER - Type   |   F1 - Hide/Show.
        /// </summary>
        public static string CommandHelperDescription {
            get {
                return ResourceManager.GetString("CommandHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players in zone.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection rejected by server.
        /// </summary>
        public static string ConnectionRejectedByServer {
            get {
                return ResourceManager.GetString("ConnectionRejectedByServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set spirit cooldown to {1} s.
        /// </summary>
        public static string CustomSpiritCooldown {
            get {
                return ResourceManager.GetString("CustomSpiritCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution error: {0}.
        /// </summary>
        public static string ExecutionError {
            get {
                return ResourceManager.GetString("ExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands: {0}.
        /// </summary>
        public static string HelpCommandHeader {
            get {
                return ResourceManager.GetString("HelpCommandHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F1 to use commands.
        /// </summary>
        public static string HintCommandsUse {
            get {
                return ResourceManager.GetString("HintCommandsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect. Incompatible SDK version..
        /// </summary>
        public static string IncompatibleVersion {
            get {
                return ResourceManager.GetString("IncompatibleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disabled infinite mana.
        /// </summary>
        public static string InfManaDisabled {
            get {
                return ResourceManager.GetString("InfManaDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enabled infinite mana.
        /// </summary>
        public static string InfManaEnabled {
            get {
                return ResourceManager.GetString("InfManaEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disabled infinite spirit energy.
        /// </summary>
        public static string InfSpiritDisabled {
            get {
                return ResourceManager.GetString("InfSpiritDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enabled infinite spirit energy.
        /// </summary>
        public static string InfSpiritEnabled {
            get {
                return ResourceManager.GetString("InfSpiritEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disabled infinite transform energy.
        /// </summary>
        public static string InfTransformDisabled {
            get {
                return ResourceManager.GetString("InfTransformDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enabled infinite transform energy.
        /// </summary>
        public static string InfTransformEnabled {
            get {
                return ResourceManager.GetString("InfTransformEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disabled infinite vessel energy.
        /// </summary>
        public static string InfVesselDisabled {
            get {
                return ResourceManager.GetString("InfVesselDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enabled infinite vessel energy.
        /// </summary>
        public static string InfVesselEnabled {
            get {
                return ResourceManager.GetString("InfVesselEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Multiplayer Lobby.
        /// </summary>
        public static string InMultiplayer {
            get {
                return ResourceManager.GetString("InMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disabled instant skill cooldown.
        /// </summary>
        public static string InstantCooldownDisabled {
            get {
                return ResourceManager.GetString("InstantCooldownDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enabled instant skill cooldown.
        /// </summary>
        public static string InstantCooldownEnabled {
            get {
                return ResourceManager.GetString("InstantCooldownEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument format: {0}.
        /// </summary>
        public static string InvalidArgumentFormat {
            get {
                return ResourceManager.GetString("InvalidArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument at index {0}. Expected {1}, got {2}.
        /// </summary>
        public static string InvalidArgumentType {
            get {
                return ResourceManager.GetString("InvalidArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command: {0}.
        /// </summary>
        public static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command format: {0}.
        /// </summary>
        public static string InvalidCommandFormat {
            get {
                return ResourceManager.GetString("InvalidCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cooldown value.
        /// </summary>
        public static string InvalidCooldown {
            get {
                return ResourceManager.GetString("InvalidCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unit name: {0}.
        /// </summary>
        public static string InvalidUnitName {
            get {
                return ResourceManager.GetString("InvalidUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of units {0}.
        /// </summary>
        public static string InvalidUnitsCount {
            get {
                return ResourceManager.GetString("InvalidUnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join other players to proceed.
        /// </summary>
        public static string JoinOtherPlayersToProceed {
            get {
                return ResourceManager.GetString("JoinOtherPlayersToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were kicked from the server..
        /// </summary>
        public static string Kicked {
            get {
                return ResourceManager.GetString("Kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master client: {0}.
        /// </summary>
        public static string MasterClient {
            get {
                return ResourceManager.GetString("MasterClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WukongMP.pak is missing.
        /// </summary>
        public static string MissingPak {
            get {
                return ResourceManager.GetString("MissingPak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string Ping {
            get {
                return ResourceManager.GetString("Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string PingUnits {
            get {
                return ResourceManager.GetString("PingUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set cooldown multiplier to {1}.
        /// </summary>
        public static string PlayerCooldown {
            get {
                return ResourceManager.GetString("PlayerCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave up.
        /// </summary>
        public static string PlayerGaveUp {
            get {
                return ResourceManager.GetString("PlayerGaveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not ready.
        /// </summary>
        public static string PlayerIsNotReady {
            get {
                return ResourceManager.GetString("PlayerIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ready.
        /// </summary>
        public static string PlayerIsReady {
            get {
                return ResourceManager.GetString("PlayerIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined!.
        /// </summary>
        public static string PlayerJoined {
            get {
                return ResourceManager.GetString("PlayerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} killed {1}.
        /// </summary>
        public static string PlayerKilledPlayer {
            get {
                return ResourceManager.GetString("PlayerKilledPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has left!.
        /// </summary>
        public static string PlayerLeft {
            get {
                return ResourceManager.GetString("PlayerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requested rebirth.
        /// </summary>
        public static string PlayerRequestedRebirth {
            get {
                return ResourceManager.GetString("PlayerRequestedRebirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} spawned {1} {2}.
        /// </summary>
        public static string PlayerSpawned {
            get {
                return ResourceManager.GetString("PlayerSpawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press J to be not ready.
        /// </summary>
        public static string PressToBeNotReady {
            get {
                return ResourceManager.GetString("PressToBeNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press J to be ready.
        /// </summary>
        public static string PressToBeReady {
            get {
                return ResourceManager.GetString("PressToBeReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press I to cancel match.
        /// </summary>
        public static string PressToCancelMatch {
            get {
                return ResourceManager.GetString("PressToCancelMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press I to play with bots.
        /// </summary>
        public static string PressToPlayWithBots {
            get {
                return ResourceManager.GetString("PressToPlayWithBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press L to switch team.
        /// </summary>
        public static string PressToSwitchTeam {
            get {
                return ResourceManager.GetString("PressToSwitchTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Red.
        /// </summary>
        public static string RedTeam {
            get {
                return ResourceManager.GetString("RedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round {0} of {1}.
        /// </summary>
        public static string RoundCount {
            get {
                return ResourceManager.GetString("RoundCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round ended. Draw.
        /// </summary>
        public static string RoundDraw {
            get {
                return ResourceManager.GetString("RoundDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round ended. {0} won.
        /// </summary>
        public static string RoundEndedWinner {
            get {
                return ResourceManager.GetString("RoundEndedWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is full, try again later..
        /// </summary>
        public static string ServerFull {
            get {
                return ResourceManager.GetString("ServerFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe packet loss detected!.
        /// </summary>
        public static string SeverePacketLossDetected {
            get {
                return ResourceManager.GetString("SeverePacketLossDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softlock. Use /softlock command to respawn.
        /// </summary>
        public static string SoftlockDetected {
            get {
                return ResourceManager.GetString("SoftlockDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators.
        /// </summary>
        public static string Spectators {
            get {
                return ResourceManager.GetString("Spectators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stalling - losing HP.
        /// </summary>
        public static string StallingMessage {
            get {
                return ResourceManager.GetString("StallingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting PvP match.
        /// </summary>
        public static string StartingGame {
            get {
                return ResourceManager.GetString("StartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too few arguments: min {0}, actual {1}.
        /// </summary>
        public static string TooFewArguments {
            get {
                return ResourceManager.GetString("TooFewArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many arguments: max {0}, actual {1}.
        /// </summary>
        public static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string TournamentDraw {
            get {
                return ResourceManager.GetString("TournamentDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner: {0}.
        /// </summary>
        public static string TournamentEndedWinner {
            get {
                return ResourceManager.GetString("TournamentEndedWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command: {0}.
        /// </summary>
        public static string UnrecognizedCommand {
            get {
                return ResourceManager.GetString("UnrecognizedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the match to end.
        /// </summary>
        public static string WaitForEnd {
            get {
                return ResourceManager.GetString("WaitForEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for other players.
        /// </summary>
        public static string WaitForOtherPlayers {
            get {
                return ResourceManager.GetString("WaitForOtherPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for other players ({0}/{1}).
        /// </summary>
        public static string WaitForOtherPlayersCount {
            get {
                return ResourceManager.GetString("WaitForOtherPlayersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are ready.
        /// </summary>
        public static string YouAreReady {
            get {
                return ResourceManager.GetString("YouAreReady", resourceCulture);
            }
        }
    }
}
