//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WukongMp.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WukongMp.Api.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Blue.
        /// </summary>
        internal static string BlueTeam {
            get {
                return ResourceManager.GetString("BlueTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        internal static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        internal static string CameraDownControls {
            get {
                return ResourceManager.GetString("CameraDownControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string CameraDownDescription {
            get {
                return ResourceManager.GetString("CameraDownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W S A D.
        /// </summary>
        internal static string CameraMoveControls {
            get {
                return ResourceManager.GetString("CameraMoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string CameraMoveDescription {
            get {
                return ResourceManager.GetString("CameraMoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMB.
        /// </summary>
        internal static string CameraRotateControls {
            get {
                return ResourceManager.GetString("CameraRotateControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string CameraRotateDescription {
            get {
                return ResourceManager.GetString("CameraRotateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string CameraUpControls {
            get {
                return ResourceManager.GetString("CameraUpControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string CameraUpDescription {
            get {
                return ResourceManager.GetString("CameraUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER - Type/Send   |   K - Hide/Show Chat.
        /// </summary>
        internal static string ChatHelperDescription {
            get {
                return ResourceManager.GetString("ChatHelperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection rejected by server.
        /// </summary>
        internal static string ConnectionRejectedByServer {
            get {
                return ResourceManager.GetString("ConnectionRejectedByServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Multiplayer Lobby.
        /// </summary>
        internal static string InMultiplayer {
            get {
                return ResourceManager.GetString("InMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command: {0}.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unit name.
        /// </summary>
        internal static string InvalidUnitName {
            get {
                return ResourceManager.GetString("InvalidUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of units.
        /// </summary>
        internal static string InvalidUnitsCount {
            get {
                return ResourceManager.GetString("InvalidUnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join other players to proceed.
        /// </summary>
        internal static string JoinOtherPlayersToProceed {
            get {
                return ResourceManager.GetString("JoinOtherPlayersToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchmaking in progress....
        /// </summary>
        internal static string MatchmakingInProgress {
            get {
                return ResourceManager.GetString("MatchmakingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WukongMP.pak is missing.
        /// </summary>
        internal static string MissingPak {
            get {
                return ResourceManager.GetString("MissingPak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Character.
        /// </summary>
        internal static string NewCharacter {
            get {
                return ResourceManager.GetString("NewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        internal static string Ping {
            get {
                return ResourceManager.GetString("Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string PingUnits {
            get {
                return ResourceManager.GetString("PingUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gave up.
        /// </summary>
        internal static string PlayerGaveUp {
            get {
                return ResourceManager.GetString("PlayerGaveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not ready.
        /// </summary>
        internal static string PlayerIsNotReady {
            get {
                return ResourceManager.GetString("PlayerIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ready.
        /// </summary>
        internal static string PlayerIsReady {
            get {
                return ResourceManager.GetString("PlayerIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined!.
        /// </summary>
        internal static string PlayerJoined {
            get {
                return ResourceManager.GetString("PlayerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} killed {1}.
        /// </summary>
        internal static string PlayerKilledPlayer {
            get {
                return ResourceManager.GetString("PlayerKilledPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has left!.
        /// </summary>
        internal static string PlayerLeft {
            get {
                return ResourceManager.GetString("PlayerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requested rebirth.
        /// </summary>
        internal static string PlayerRequestedRebirth {
            get {
                return ResourceManager.GetString("PlayerRequestedRebirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} spawned {1} {2}.
        /// </summary>
        internal static string PlayerSpawned {
            get {
                return ResourceManager.GetString("PlayerSpawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press J to be not ready.
        /// </summary>
        internal static string PressToBeNotReady {
            get {
                return ResourceManager.GetString("PressToBeNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press J to be ready.
        /// </summary>
        internal static string PressToBeReady {
            get {
                return ResourceManager.GetString("PressToBeReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press I to cancel match.
        /// </summary>
        internal static string PressToCancelMatch {
            get {
                return ResourceManager.GetString("PressToCancelMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press I to play with bots.
        /// </summary>
        internal static string PressToPlayWithBots {
            get {
                return ResourceManager.GetString("PressToPlayWithBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press L to switch team.
        /// </summary>
        internal static string PressToSwitchTeam {
            get {
                return ResourceManager.GetString("PressToSwitchTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Join.
        /// </summary>
        internal static string QuickJoin {
            get {
                return ResourceManager.GetString("QuickJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Red.
        /// </summary>
        internal static string RedTeam {
            get {
                return ResourceManager.GetString("RedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round {0} of {1}.
        /// </summary>
        internal static string RoundCount {
            get {
                return ResourceManager.GetString("RoundCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round ended. Draw.
        /// </summary>
        internal static string RoundDraw {
            get {
                return ResourceManager.GetString("RoundDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round ended. {0} won.
        /// </summary>
        internal static string RoundEndedWinner {
            get {
                return ResourceManager.GetString("RoundEndedWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Character.
        /// </summary>
        internal static string SelectCharacter {
            get {
                return ResourceManager.GetString("SelectCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators.
        /// </summary>
        internal static string Spectators {
            get {
                return ResourceManager.GetString("Spectators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting PvP match.
        /// </summary>
        internal static string StartingGame {
            get {
                return ResourceManager.GetString("StartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string TournamentDraw {
            get {
                return ResourceManager.GetString("TournamentDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner: {0}.
        /// </summary>
        internal static string TournamentEndedWinner {
            get {
                return ResourceManager.GetString("TournamentEndedWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the match to end.
        /// </summary>
        internal static string WaitForEnd {
            get {
                return ResourceManager.GetString("WaitForEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for other players.
        /// </summary>
        internal static string WaitForOtherPlayers {
            get {
                return ResourceManager.GetString("WaitForOtherPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are ready.
        /// </summary>
        internal static string YouAreReady {
            get {
                return ResourceManager.GetString("YouAreReady", resourceCulture);
            }
        }
    }
}
