<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
        <LangVersion>latest</LangVersion>
        <OutputType>Library</OutputType>
        <AssemblyName>WukongMpMod</AssemblyName>
        <RootNamespace>WukongMpMod</RootNamespace>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <BuildTimestamp>$([System.DateTime]::UtcNow.ToString("yyyyMMdd.HHmm"))</BuildTimestamp>
        <FileVersion>1.0.0.$(BuildTimestamp)</FileVersion>
        <InformationalVersion>1.0.0.$(BuildTimestamp)</InformationalVersion>
    </PropertyGroup>

    <Target Name="PrintBuildVersion" AfterTargets="AfterBuild">
        <Message Importance="High" Text="Build Version: $(InformationalVersion)"/>
    </Target>

    <ItemGroup>
        <ProjectReference Include="..\WukongApi\WukongApi.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="CSharpModBase">
            <HintPath>..\WukongApi\Core\CSharpModBase.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
