<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;NoDisconnect;Testing</Configurations>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\readym-gameserver\src\ReadyM.Api.Generators\ReadyM.Api.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
        <ProjectReference Include="..\WukongMp.Sdk\WukongMp.Sdk.csproj"/>
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

    <ItemGroup>
      <None Update="manifest.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>


    <ItemGroup>
        <!-- Reference-only assemblies for the game. Compile-time only, the real
             assemblies are already loaded in the game process at runtime. -->
        <PackageReference Include="ReadyM.Wukong.GameRefs" Version="1.0.21.23831-preview.1" />
    </ItemGroup>
</Project>
