<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <ImplicitUsings>false</ImplicitUsings>
        <LangVersion>7.3</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WukongMp.Common\WukongMp.Common.csproj" />
    </ItemGroup>

</Project>
