using BtlB1;
using BtlShare;
using System.Collections.Generic;

namespace WukongApi
{
    public static class MonkeyBotConfig
    {
        public static Dictionary<EquipPosition, int> Equipment = new()
        {
            { EquipPosition.Head, 12001},
            { EquipPosition.Upwear, 12002},
            { EquipPosition.Arm, 12003},
            { EquipPosition.Foot, 12004},
            { EquipPosition.Hulu, 18011},
            { EquipPosition.Weapon, 15002},
            { EquipPosition.Fabao, 19002}
        };

        public static Dictionary<EBGUAttrFloat, float> Attribues = new()
        {
            { EBGUAttrFloat.B1StunMax, 0 },
            { EBGUAttrFloat.SkillSuperArmorMax, 10000 },
            { EBGUAttrFloat.BlockCollapseArmorMax, 1000 },
            { EBGUAttrFloat.BlindSlotMax, 100 },
            { EBGUAttrFloat.HpMaxMul, 0 },
            { EBGUAttrFloat.MpMaxMul, 0 },
            { EBGUAttrFloat.AtkMul, 2500 },
            { EBGUAttrFloat.DefMul, 0 },
            { EBGUAttrFloat.B1StunMaxMul, 0 },
            { EBGUAttrFloat.StaminaDepletedLimitMul, 0 },
            { EBGUAttrFloat.StaminaMaxMul, 0 },
            { EBGUAttrFloat.StaminaRecoverMul, 6000 },
            { EBGUAttrFloat.KptturnSpeedMul, 0 },
            { EBGUAttrFloat.FreezeAbnormalAccMaxMul, 0.5f },
            { EBGUAttrFloat.BurnAbnormalAccMaxMul, 0.5f },
            { EBGUAttrFloat.PoisonAbnormalAccMaxMul, 0.5f },
            { EBGUAttrFloat.ThunderAbnormalAccMaxMul, 0.5f },
            { EBGUAttrFloat.YinAbnormalAccMaxMul, 0 },
            { EBGUAttrFloat.YangAbnormalAccMaxMul, 0 },
            { EBGUAttrFloat.StaminaCostMultiperMul, 0 },
            { EBGUAttrFloat.TransEnergyMaxMul, 2000 },
            { EBGUAttrFloat.EnergyMinConsumeMul, 0 },
            { EBGUAttrFloat.EnergyConsumeSpeedMul, -1000 },
            { EBGUAttrFloat.EnergyIncreaseSpeedMul, 1200 },
            { EBGUAttrFloat.HpMaxBase, 905 },
            { EBGUAttrFloat.MpMaxBase, 500 },
            { EBGUAttrFloat.AtkBase, 167 },
            { EBGUAttrFloat.DefBase, 515 },
            { EBGUAttrFloat.B1StunMaxBase, 10000 },
            { EBGUAttrFloat.StaminaDepletedLimitBase, 80 },
            { EBGUAttrFloat.StaminaMaxBase, 500 },
            { EBGUAttrFloat.StaminaRecoverBase, 86 },
            { EBGUAttrFloat.SkillSuperArmorMaxBase, 0 },
            { EBGUAttrFloat.CritRateBase, 1600 },
            { EBGUAttrFloat.CritMultiplierBase, 3900 },
            { EBGUAttrFloat.TenacityBase, 0 },
            { EBGUAttrFloat.KptturnSpeedBase, 270 },
            { EBGUAttrFloat.EarPlugBase, 0 },
            { EBGUAttrFloat.CritRateDefBase, 0 },
            { EBGUAttrFloat.CritDmgMulDefBase, 0 },
            { EBGUAttrFloat.DmgAdditionBase, 0 },
            { EBGUAttrFloat.DmgDefBase, 2700 },
            { EBGUAttrFloat.BlockCollapseArmorMaxBase, 0 },
            { EBGUAttrFloat.DingshenDefAdditionBase, 0 },
            { EBGUAttrFloat.FreezeAbnormalAccMaxBase, 100 },
            { EBGUAttrFloat.BurnAbnormalAccMaxBase, 100 },
            { EBGUAttrFloat.PoisonAbnormalAccMaxBase, 100 },
            { EBGUAttrFloat.ThunderAbnormalAccMaxBase, 100 },
            { EBGUAttrFloat.FreezeAtkBase, 14 },
            { EBGUAttrFloat.BurnAtkBase, 14 },
            { EBGUAttrFloat.PoisonAtkBase, 14 },
            { EBGUAttrFloat.ThunderAtkBase, 14 },
            { EBGUAttrFloat.FreezeDefBase, 117 },
            { EBGUAttrFloat.BurnDefBase, 117 },
            { EBGUAttrFloat.PoisonDefBase, 45 },
            { EBGUAttrFloat.ThunderDefBase, 45 },
            { EBGUAttrFloat.BloodBottomNumMaxBase, 1 },
            { EBGUAttrFloat.PelevelMaxBase, 0 },
            { EBGUAttrFloat.ShieldMaxBase, 9999 },
            { EBGUAttrFloat.PevalueMaxBase, 480 },
            { EBGUAttrFloat.YinAbnormalAccMaxBase, 100 },
            { EBGUAttrFloat.YangAbnormalAccMaxBase, 100 },
            { EBGUAttrFloat.YinAtkBase, 0 },
            { EBGUAttrFloat.YangAtkBase, 0 },
            { EBGUAttrFloat.YinDefBase, 0 },
            { EBGUAttrFloat.YangDefBase, 0 },
            { EBGUAttrFloat.StaminaCostMultiperBase, 1 },
            { EBGUAttrFloat.TransEnergyMaxBase, 0 },
            { EBGUAttrFloat.EnergyMinConsumeBase, 0 },
            { EBGUAttrFloat.EnergyConsumeSpeedBase, 0 },
            { EBGUAttrFloat.EnergyIncreaseSpeedBase, 0 },
            { EBGUAttrFloat.B1Stun, 0 },
            { EBGUAttrFloat.SkillSuperArmor, 10000 },
            { EBGUAttrFloat.BlockCollapseArmor, 1000 },
            { EBGUAttrFloat.FreezeAbnormalAcc, 0 },
            { EBGUAttrFloat.BurnAbnormalAcc, 0 },
            { EBGUAttrFloat.PoisonAbnormalAcc, 0 },
            { EBGUAttrFloat.ThunderAbnormalAcc, 0 },
            { EBGUAttrFloat.BlindSlot, 100 },
            { EBGUAttrFloat.BloodBottomNum, 1 },
            { EBGUAttrFloat.Pelevel, 0 },
            { EBGUAttrFloat.Shield, 0 },
            { EBGUAttrFloat.Pevalue, 0 },
            { EBGUAttrFloat.YinAbnormalAcc, 0 },
            { EBGUAttrFloat.YangAbnormalAcc, 0 },
            { EBGUAttrFloat.ExpDropAddition, 0 },
            { EBGUAttrFloat.SpiritDropAddition, 0 },
            { EBGUAttrFloat.CommDropAddition, 0 },
            { EBGUAttrFloat.Hp, 875 }
        };
    }
}
