<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <OutputType>Library</OutputType>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <RootNamespace>WukongMp.PvP</RootNamespace>
        <TargetName>WukongMp.PvP</TargetName>
        <Configurations>Debug;Release;NoDisconnect;Testing</Configurations>
        <Platforms>AnyCPU</Platforms>
        <TargetFramework>netstandard2.0</TargetFramework>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <Target Name="PrintBuildVersion" AfterTargets="AfterBuild">
        <Message Importance="High" Text="Build Version: $(InformationalVersion)" />
    </Target>

    <ItemGroup>
        <ProjectReference Include="..\readym-gameserver\src\ReadyM.Api.Generators\ReadyM.Api.Generators.csproj" />
        <ProjectReference Include="..\WukongMp.Api\WukongMp.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="CSharpModBase">
            <HintPath>..\WukongMp.Api\Core\CSharpModBase.dll</HintPath>
        </Reference>
        <Reference Include="CSharpModBaseV2">
            <HintPath>..\WukongMp.Api\Core\CSharpModBaseV2.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
