<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>13</LangVersion>
        <OutputType>Library</OutputType>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <DebugType>portable</DebugType>
        <PackageId>WukongMp.Api</PackageId>
        <RootNamespace>WukongMp.Api</RootNamespace>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>CS8600;CS8602;CS8603;CS8604;CS8618;CS8625;CS8619</WarningsAsErrors>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release;NoDisconnect;Testing</Configurations>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <Platforms>AnyCPU</Platforms>
        <TargetFramework>netstandard2.0</TargetFramework>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    
    <ItemGroup>
        <Reference Include="Harmony">
            <HintPath>Core\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="PreludeLib">
            <HintPath>Core\PreludeLib.dll</HintPath>
        </Reference>
        <Reference Include="CSharpModBase">
            <HintPath>Core\CSharpModBase.dll</HintPath>
        </Reference>
        <Reference Include="CSharpModBase">
            <HintPath>Core\CSharpModBaseV2.dll</HintPath>
        </Reference>

        <Reference Include="b1.Managed">
            <HintPath>Game\b1.Managed.dll</HintPath>
        </Reference>
        <Reference Include="b1.Native">
            <HintPath>Game\b1.Native.dll</HintPath>
        </Reference>
        <Reference Include="b1.NativePlugins">
            <HintPath>Game\b1.NativePlugins.dll</HintPath>
        </Reference>
        <Reference Include="B1UI_GSE.Script">
            <HintPath>Game\B1UI_GSE.Script.dll</HintPath>
        </Reference>
        <Reference Include="BtlSvr.Main">
            <HintPath>Game\BtlSvr.Main.dll</HintPath>
        </Reference>
        <Reference Include="Diana.Client.Common">
            <HintPath>Game\Diana.Client.Common.dll</HintPath>
        </Reference>
        <Reference Include="Diana.Common">
            <HintPath>Game\Diana.Common.dll</HintPath>
        </Reference>
        <Reference Include="Diana.Server.Common">
            <HintPath>Game\Diana.Server.Common.dll</HintPath>
        </Reference>
        <Reference Include="Google.Protobuf">
            <HintPath>Game\Google.Protobuf.dll</HintPath>
        </Reference>
        <Reference Include="GSE.Core">
            <HintPath>Game\GSE.Core.dll</HintPath>
        </Reference>
        <Reference Include="GSE.GSNet">
            <HintPath>Game\GSE.GSNet.dll</HintPath>
        </Reference>
        <Reference Include="GSE.GSSdk">
            <HintPath>Game\GSE.GSSdk.dll</HintPath>
        </Reference>
        <Reference Include="GSE.OnlineBase">
            <HintPath>Game\GSE.OnlineBase.dll</HintPath>
        </Reference>
        <Reference Include="GSE.ProtobufDB">
            <HintPath>Game\GSE.ProtobufDB.dll</HintPath>
        </Reference>
        <Reference Include="GUR.Runtime">
            <HintPath>Game\GUR.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="ICSharpCode.SharpZipLib">
            <HintPath>Game\ICSharpCode.SharpZipLib.dll</HintPath>
        </Reference>
        <Reference Include="ILRuntime">
            <HintPath>Game\ILRuntime.dll</HintPath>
        </Reference>
        <Reference Include="ILRuntime.Mono.Cecil">
            <HintPath>Game\ILRuntime.Mono.Cecil.dll</HintPath>
        </Reference>
        <Reference Include="ILRuntime.Mono.Cecil.Mdb">
            <HintPath>Game\ILRuntime.Mono.Cecil.Mdb.dll</HintPath>
        </Reference>
        <Reference Include="ILRuntime.Mono.Cecil.Pdb">
            <HintPath>Game\ILRuntime.Mono.Cecil.Pdb.dll</HintPath>
        </Reference>
        <Reference Include="LitJson">
            <HintPath>Game\LitJson.dll</HintPath>
        </Reference>
        <Reference Include="Mono.Cecil">
            <HintPath>Game\Mono.Cecil.dll</HintPath>
        </Reference>
        <Reference Include="Mono.Data.Sqlite">
            <HintPath>Game\Mono.Data.Sqlite.dll</HintPath>
        </Reference>
        <Reference Include="Mono.Posix">
            <HintPath>Game\Mono.Posix.dll</HintPath>
        </Reference>
        <Reference Include="Mono.Security">
            <HintPath>Game\Mono.Security.dll</HintPath>
        </Reference>
        <Reference Include="Mono.WebBrowser">
            <HintPath>Game\Mono.WebBrowser.dll</HintPath>
        </Reference>
        <Reference Include="Novell.Directory.Ldap">
            <HintPath>Game\Novell.Directory.Ldap.dll</HintPath>
        </Reference>
        <Reference Include="Protobuf.RunTime">
            <HintPath>Game\Protobuf.RunTime.dll</HintPath>
        </Reference>
        <Reference Include="Sentry">
            <HintPath>Game\Sentry.dll</HintPath>
        </Reference>
        <Reference Include="System.Buffers">
            <HintPath>Game\System.Buffers.dll</HintPath>
        </Reference>
        <Reference Include="System.IO.FileSystem">
            <HintPath>Game\System.IO.FileSystem.dll</HintPath>
        </Reference>
        <Reference Include="System.Numerics.Vectors">
            <HintPath>Game\System.Numerics.Vectors.dll</HintPath>
        </Reference>
        <Reference Include="System.ServiceModel.Internals">
            <HintPath>Game\System.ServiceModel.Internals.dll</HintPath>
        </Reference>
        <Reference Include="System.Threading.Tasks.Extensions">
            <HintPath>Game\System.Threading.Tasks.Extensions.dll</HintPath>
        </Reference>
        <Reference Include="UnrealEngine">
            <HintPath>Game\UnrealEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnrealEngine.Runtime">
            <HintPath>Game\UnrealEngine.Runtime.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        <PackageReference Include="HttpMachine.PCL" Version="5.0.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="Microsoft.Bcl.Memory" Version="9.0.5" />
        <PackageReference Include="Microsoft.Bcl.Numerics" Version="9.0.5" />
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.6" />
        <PackageReference Include="Mono.Cecil" Version="0.11.5" />
        <PackageReference Include="System.Buffers" Version="4.5.1" />
        <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
        <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
        <PackageReference Include="System.Memory" Version="4.5.5" />
        <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
        <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
        <PackageReference Include="System.Reflection.Metadata" Version="8.0.0" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
        <PackageReference Include="System.Text.Encodings.Web" Version="9.0.6" />
        <PackageReference Include="System.Text.Json" Version="9.0.6" />
        <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
        <PackageReference Include="Nito.AsyncEx.Context" Version="5.1.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\readym-gameserver\src\Friflo.Engine.ECS\src\ECS\Friflo.Engine.ECS.csproj" />
        <ProjectReference Include="..\readym-gameserver\src\ReadyM.Api.Multiplayer\ReadyM.Api.Multiplayer.csproj" />
        <ProjectReference Include="..\readym-gameserver\src\ReadyM.Api.Generators\ReadyM.Api.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
        <ProjectReference Include="..\readym-gameserver\src\ReadyM.Relay.Client\ReadyM.Relay.Client.csproj" />
        <ProjectReference Include="..\readym-gameserver\src\ReadyM.Relay.Common.Wukong\ReadyM.Relay.Common.Wukong.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Resources\Texts.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Texts.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Texts.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Texts.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Resources\Texts.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Texts.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Texts.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Texts.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>